### ISSUE TITLE
If graphite host resolves to a different IP jmx2graphite fails forever

### ISSUE THREAD

**Issue by asafm** [logzio/jmx2graphite#6] opened 2016-05-30 10:49 UTC
Sometimes upon deployment of graphite you change its IP. jmx2graphite never recovers from it until restarted. 
The solution is to refresh DNS upon connection timeout, or to simply create a new connection which should resolve DNS again

**Comment by roiravhon** [comment] 2016-05-30 10:56
+1

**Comment by kyle-hamlin** [comment] 2019-07-19 16:01
Could this be an issue in a kubernetes setup where you run jmx2graphite as a sidecar in a pod?

**Comment by asafm** [comment] 2019-08-12 08:35
Not sidecar, but when running in a Docker Container on machine

**Comment by electron0zero** [comment] 2019-09-25 13:59
I am also running into same issue.
when my graphite server restarts, jmx2graphite fails until restarted manually.
it fails with broken pipe error for me

**Comment by electron0zero** [comment] 2020-02-10 21:25
running latest version and still getting this error.

```
20/02/10 21:12:54 INFO jmx2graphite.MetricsPipeline: Found 122 metric beans. Time = 21ms, for 2020-02-10T21:12:00.000+0000
20/02/10 21:12:54 INFO jmx2graphite.MetricsPipeline: Filtered out 0 metrics out of 122 after white/blacklisting
20/02/10 21:12:54 INFO jmx2graphite.MetricsPipeline: metrics fetched. Time: 74 ms; Metrics: 296
20/02/10 21:12:54 WARN jmx2graphite.MetricsPipeline: Failed writing to Graphite: Failed writing metric to graphite. Error = Broken pipe (Write failed)
```

I think this error comes from https://github.com/logzio/jmx2graphite/blob/2a7190a4a800be5cefead867ecd1ca7ed3a8e4bd/src/main/java/io/logz/jmx2graphite/MetricsPipeline.java#L92

I see that it calls sendMetrics and there there is a method to check connection, See: https://github.com/logzio/jmx2graphite/blob/2a7190a4a8/src/main/java/io/logz/jmx2graphite/GraphiteClient.java#L97

so this should not be failing, unless call to connect fails

**Comment by asafm** [comment] 2020-02-11 06:46
I believe to fix should be: wrap code inside sendMetrics() such that if we got IOException of type broken pipe, we should reconnect and try again (maybe using Failsafe)
@yyyogev : I think this is a great opportunity to introduce to test the fix, using Testcontainers-java project to spin up a real Graphite.

**Comment by ChristophKreutzer23** [comment] 2020-08-11 05:40
Hi, 

as described in my pull request, this is a crude fix and I hope it works, since I could not reproduce the Exception. I tried using Testcontainers and using a local Container running Graphite. But I did not manage to reproduce the correct Exception. If anybody has some pointers for me concerning the test setup or the fix, please share them and I will rework my fix.

Basically I went for @asafm s suggestion and cought IOExceptions and checked for a message containing "broken pipe", closing the connection and calling sendMetrics again (which in turn will check for connection and reconnect).

**Comment by mattwhittingham** [comment] 2020-08-14 17:18
So this problem, is really frustrating.  It requires mass reboots of our apps to make the sending work again.  Can we get this PR reviewed?   Also, it looks like the pickle client handles the broken pipe.  Is that what you guys have configured?

**Comment by asafm** [comment] 2020-08-16 08:05
@mattwhittingham - I've started working on this PR

**Comment by ChristophKreutzer23** [comment] 2020-09-07 06:12
Hey,

I just realized I didn't leave another comment here, when I pushed my new solution to the problem. I don't know if you saw my recent change or maybe even had a chance to take a look at it and potentially have any remarks?

**Comment by asafm** [comment] 2020-10-11 18:18
@ChristophKreutzer23 Sorry mate, I was awfully busy past 5 weeks. I reviewed your PR and waiting for your fixes. Great work.

**Comment by ChristophKreutzer23** [comment] 2020-11-16 07:17
Hey, sorry for being inactive this long. I finally was able to put some time in to address your remarks. Since I kind of messed up my repo/master branch, I started a new pull request, sorry for the inconvenience.

**Closed as completed** 2020-12-01 14:54 UTC

**Comment by yzargari** [comment] 2020-12-30 07:18
@asafm / @yyyogev - when is the next release containing this fix?

EDIT: I see that 1.5.0 was released last night. Thanks!
